---
title: "Lockdown Severity Index TODOs"
output: html_notebook
---

# To-Do list

- write code to pull csv from the kff github page
  * https://github.com/KFFData/COVID-19-Data/tree/kff_master/State%20Policy%20Actions/State%20Social%20Distancing%20Actions
  * ~~talk to them about data ending 12/18/2020. Can't access on wayback, and the git readme says "Data is reviewed and updated daily. If there are no changes, the most recent data reflects current policy actions."~~ *fixed when they uploaded old data on 1/11/2021. Looks like they'll maintain moving forward*
  * ~~will need to write a chunk to change date format (or change my existing date format)~~ *wrote code to handle the two different csv structures and from two different folders and to reorder according to date, not numeric.*
  * ~~find out how to download inside R instead of manual~~
  
- ReadMe
  * ~~Abstract~~
  * Rational for standardizing and population-weighting (and novelty)
  * ~~Data input descriptions~~
  * Methodology

- Better way of interpolating than using the for-loop
  * i end point is un-intuitive
  * throws error and stops sourcing, so it fails to write the output
  
- Reorganize the plot script
  * pull out the data into separate script
  * or at least re-organize to have a plot right after its dplyr chain. 
  
- Actually, I want to split the script into three:
  * Individual state series (both plain and std)
  * category (both plain and std)
  * us aggregated series (both plain and pop-std)
  
- ~~Get better poplulation dataframe, one that can be exported.~~

- ~~make footnote dates dynamic~~

- make footnotes tex expressions

- pull out plot titles, footnotes into separate string
